name: image-chef

x-image-chef-api: &image-chef-api-env
  CORS_ALLOW_ORIGIN: http://localhost:3000,https://image-chef-client.purpleground-1a74af37.eastus.azurecontainerapps.io
  FLUX_SCHNELL: api/image_chef_api/models/FLUX.1-schnell
  FLUX_FILL: api/image_chef_api/FLUX.1-Fill-dev
  FLUX_REFINEMENT: api/image_chef_api/models/FLUX.1-dev-Controlnet-Inpainting-Beta

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
    environment:
      <<: [*image-chef-api-env]
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: "http://localhost:8000"
